SET(OPENNURBS_DIR not_valid CACHE PATH "openNURBS 5.0 source directory")

if(${OPENNURBS_DIR} STREQUAL not_valid)
  message(FATAL_ERROR "Error, opennurbs directory not found.")
endif()

include_directories(${OPENNURBS_DIR})

SET(SOURCE_CPP
    ${OPENNURBS_DIR}/opennurbs_3dm_attributes.cpp
    ${OPENNURBS_DIR}/opennurbs_3dm_properties.cpp
    ${OPENNURBS_DIR}/opennurbs_3dm_settings.cpp
    ${OPENNURBS_DIR}/opennurbs_annotation2.cpp
    ${OPENNURBS_DIR}/opennurbs_annotation.cpp
    ${OPENNURBS_DIR}/opennurbs_arc.cpp
    ${OPENNURBS_DIR}/opennurbs_arccurve.cpp
    ${OPENNURBS_DIR}/opennurbs_archive.cpp
    ${OPENNURBS_DIR}/opennurbs_array.cpp
    ${OPENNURBS_DIR}/opennurbs_base32.cpp
    ${OPENNURBS_DIR}/opennurbs_base64.cpp
    ${OPENNURBS_DIR}/opennurbs_beam.cpp
    ${OPENNURBS_DIR}/opennurbs_bezier.cpp
    ${OPENNURBS_DIR}/opennurbs_beziervolume.cpp
    ${OPENNURBS_DIR}/opennurbs_bitmap.cpp
    ${OPENNURBS_DIR}/opennurbs_bounding_box.cpp
    ${OPENNURBS_DIR}/opennurbs_box.cpp
    ${OPENNURBS_DIR}/opennurbs_brep.cpp
    ${OPENNURBS_DIR}/opennurbs_brep_extrude.cpp
    ${OPENNURBS_DIR}/opennurbs_brep_io.cpp
    ${OPENNURBS_DIR}/opennurbs_brep_isvalid.cpp
    ${OPENNURBS_DIR}/opennurbs_brep_region.cpp
    ${OPENNURBS_DIR}/opennurbs_brep_tools.cpp
    ${OPENNURBS_DIR}/opennurbs_brep_v2valid.cpp
    ${OPENNURBS_DIR}/opennurbs_circle.cpp
    ${OPENNURBS_DIR}/opennurbs_color.cpp
    ${OPENNURBS_DIR}/opennurbs_compress.cpp
    ${OPENNURBS_DIR}/opennurbs_cone.cpp
    ${OPENNURBS_DIR}/opennurbs_crc.cpp
    ${OPENNURBS_DIR}/opennurbs_curve.cpp
    ${OPENNURBS_DIR}/opennurbs_curveonsurface.cpp
    ${OPENNURBS_DIR}/opennurbs_curveproxy.cpp
    ${OPENNURBS_DIR}/opennurbs_cylinder.cpp
    ${OPENNURBS_DIR}/opennurbs_defines.cpp
    ${OPENNURBS_DIR}/opennurbs_detail.cpp
    ${OPENNURBS_DIR}/opennurbs_dimstyle.cpp
    ${OPENNURBS_DIR}/opennurbs_dll.cpp
    ${OPENNURBS_DIR}/opennurbs_ellipse.cpp
    ${OPENNURBS_DIR}/opennurbs_embedded_file.cpp
    ${OPENNURBS_DIR}/opennurbs_error.cpp
    ${OPENNURBS_DIR}/opennurbs_error_message.cpp
    ${OPENNURBS_DIR}/opennurbs_evaluate_nurbs.cpp
    ${OPENNURBS_DIR}/opennurbs_extensions.cpp
    ${OPENNURBS_DIR}/opennurbs_font.cpp
    ${OPENNURBS_DIR}/opennurbs_fsp.cpp
    ${OPENNURBS_DIR}/opennurbs_geometry.cpp
    #opennurbs_gl.cpp
    ${OPENNURBS_DIR}/opennurbs_group.cpp
    ${OPENNURBS_DIR}/opennurbs_hatch.cpp
    ${OPENNURBS_DIR}/opennurbs_instance.cpp
    ${OPENNURBS_DIR}/opennurbs_intersect.cpp
    ${OPENNURBS_DIR}/opennurbs_knot.cpp
    ${OPENNURBS_DIR}/opennurbs_layer.cpp
    ${OPENNURBS_DIR}/opennurbs_light.cpp
    ${OPENNURBS_DIR}/opennurbs_line.cpp
    ${OPENNURBS_DIR}/opennurbs_linecurve.cpp
    ${OPENNURBS_DIR}/opennurbs_linetype.cpp
    ${OPENNURBS_DIR}/opennurbs_lookup.cpp
    ${OPENNURBS_DIR}/opennurbs_material.cpp
    ${OPENNURBS_DIR}/opennurbs_math.cpp
    ${OPENNURBS_DIR}/opennurbs_matrix.cpp
    ${OPENNURBS_DIR}/opennurbs_memory.c
    ${OPENNURBS_DIR}/opennurbs_memory_util.c
    ${OPENNURBS_DIR}/opennurbs_mesh.cpp
    ${OPENNURBS_DIR}/opennurbs_mesh_ngon.cpp
    ${OPENNURBS_DIR}/opennurbs_mesh_tools.cpp
    ${OPENNURBS_DIR}/opennurbs_morph.cpp
    ${OPENNURBS_DIR}/opennurbs_nurbscurve.cpp
    ${OPENNURBS_DIR}/opennurbs_nurbssurface.cpp
    ${OPENNURBS_DIR}/opennurbs_nurbsvolume.cpp
    ${OPENNURBS_DIR}/opennurbs_object.cpp
    ${OPENNURBS_DIR}/opennurbs_object_history.cpp
    ${OPENNURBS_DIR}/opennurbs_objref.cpp
    ${OPENNURBS_DIR}/opennurbs_offsetsurface.cpp
    ${OPENNURBS_DIR}/opennurbs_optimize.cpp
    ${OPENNURBS_DIR}/opennurbs_plane.cpp
    ${OPENNURBS_DIR}/opennurbs_planesurface.cpp
    ${OPENNURBS_DIR}/opennurbs_pluginlist.cpp
    ${OPENNURBS_DIR}/opennurbs_pointcloud.cpp
    ${OPENNURBS_DIR}/opennurbs_point.cpp
    ${OPENNURBS_DIR}/opennurbs_pointgeometry.cpp
    ${OPENNURBS_DIR}/opennurbs_pointgrid.cpp
    ${OPENNURBS_DIR}/opennurbs_polycurve.cpp
    ${OPENNURBS_DIR}/opennurbs_polyedgecurve.cpp
    ${OPENNURBS_DIR}/opennurbs_polyline.cpp
    ${OPENNURBS_DIR}/opennurbs_polylinecurve.cpp
    ${OPENNURBS_DIR}/opennurbs_precompiledheader.cpp
    ${OPENNURBS_DIR}/opennurbs_rand.cpp
    ${OPENNURBS_DIR}/opennurbs_revsurface.cpp
    ${OPENNURBS_DIR}/opennurbs_rtree.cpp
    ${OPENNURBS_DIR}/opennurbs_sort.cpp
    ${OPENNURBS_DIR}/opennurbs_sphere.cpp
    ${OPENNURBS_DIR}/opennurbs_string.cpp
    ${OPENNURBS_DIR}/opennurbs_sum.cpp
    ${OPENNURBS_DIR}/opennurbs_sumsurface.cpp
    ${OPENNURBS_DIR}/opennurbs_surface.cpp
    ${OPENNURBS_DIR}/opennurbs_surfaceproxy.cpp
    ${OPENNURBS_DIR}/opennurbs_textlog.cpp
    ${OPENNURBS_DIR}/opennurbs_torus.cpp
    ${OPENNURBS_DIR}/opennurbs_unicode.cpp
    ${OPENNURBS_DIR}/opennurbs_userdata.cpp
    ${OPENNURBS_DIR}/opennurbs_uuid.cpp
    ${OPENNURBS_DIR}/opennurbs_viewport.cpp
    ${OPENNURBS_DIR}/opennurbs_workspace.cpp
    ${OPENNURBS_DIR}/opennurbs_wstring.cpp
    ${OPENNURBS_DIR}/opennurbs_xform.cpp
    ${OPENNURBS_DIR}/opennurbs_zlib.cpp
    ${OPENNURBS_DIR}/opennurbs_zlib_memory.cpp
    ${OPENNURBS_DIR}/zlib/adler32.c
    ${OPENNURBS_DIR}/zlib/compress.c
    ${OPENNURBS_DIR}/zlib/crc32.c
    ${OPENNURBS_DIR}/zlib/deflate.c
    ${OPENNURBS_DIR}/zlib/infback.c
    ${OPENNURBS_DIR}/zlib/inffast.c
    ${OPENNURBS_DIR}/zlib/inflate.c
    ${OPENNURBS_DIR}/zlib/inftrees.c
    ${OPENNURBS_DIR}/zlib/trees.c
    ${OPENNURBS_DIR}/zlib/uncompr.c
    ${OPENNURBS_DIR}/zlib/zutil.c
)

SET(SOURCE_H
    ${OPENNURBS_DIR}/opennurbs_3dm_attributes.h
    ${OPENNURBS_DIR}/opennurbs_3dm.h
    ${OPENNURBS_DIR}/opennurbs_3dm_properties.h
    ${OPENNURBS_DIR}/opennurbs_3dm_settings.h
    ${OPENNURBS_DIR}/opennurbs_annotation2.h
    ${OPENNURBS_DIR}/opennurbs_annotation.h
    ${OPENNURBS_DIR}/opennurbs_arccurve.h
    ${OPENNURBS_DIR}/opennurbs_arc.h
    ${OPENNURBS_DIR}/opennurbs_archive.h
    ${OPENNURBS_DIR}/opennurbs_array_defs.h
    ${OPENNURBS_DIR}/opennurbs_array.h
    ${OPENNURBS_DIR}/opennurbs_base32.h
    ${OPENNURBS_DIR}/opennurbs_base64.h
    ${OPENNURBS_DIR}/opennurbs_beam.h
    ${OPENNURBS_DIR}/opennurbs_bezier.h
    ${OPENNURBS_DIR}/opennurbs_bitmap.h
    ${OPENNURBS_DIR}/opennurbs_bounding_box.h
    ${OPENNURBS_DIR}/opennurbs_box.h
    ${OPENNURBS_DIR}/opennurbs_brep.h
    ${OPENNURBS_DIR}/opennurbs_circle.h
    ${OPENNURBS_DIR}/opennurbs_color.h
    ${OPENNURBS_DIR}/opennurbs_compress.h
    ${OPENNURBS_DIR}/opennurbs_cone.h
    ${OPENNURBS_DIR}/opennurbs_crc.h
    ${OPENNURBS_DIR}/opennurbs_curve.h
    ${OPENNURBS_DIR}/opennurbs_curveonsurface.h
    ${OPENNURBS_DIR}/opennurbs_curveproxy.h
    ${OPENNURBS_DIR}/opennurbs_cylinder.h
    ${OPENNURBS_DIR}/opennurbs_defines.h
    ${OPENNURBS_DIR}/opennurbs_detail.h
    ${OPENNURBS_DIR}/opennurbs_dimstyle.h
    ${OPENNURBS_DIR}/opennurbs_dll_resource.h
    ${OPENNURBS_DIR}/opennurbs_ellipse.h
    ${OPENNURBS_DIR}/opennurbs_error.h
    ${OPENNURBS_DIR}/opennurbs_evaluate_nurbs.h
    ${OPENNURBS_DIR}/opennurbs_extensions.h
    ${OPENNURBS_DIR}/opennurbs_font.h
    ${OPENNURBS_DIR}/opennurbs_fpoint.h
    ${OPENNURBS_DIR}/opennurbs_fsp_defs.h
    ${OPENNURBS_DIR}/opennurbs_fsp.h
    ${OPENNURBS_DIR}/opennurbs_geometry.h
    #${OPENNURBS_DIR}/opennurbs_gl.h
    ${OPENNURBS_DIR}/opennurbs_group.h
    ${OPENNURBS_DIR}/opennurbs.h
    ${OPENNURBS_DIR}/opennurbs_hatch.h
    ${OPENNURBS_DIR}/opennurbs_hsort_template.h
    ${OPENNURBS_DIR}/opennurbs_instance.h
    ${OPENNURBS_DIR}/opennurbs_intersect.h
    ${OPENNURBS_DIR}/opennurbs_knot.h
    ${OPENNURBS_DIR}/opennurbs_layer.h
    ${OPENNURBS_DIR}/opennurbs_light.h
    ${OPENNURBS_DIR}/opennurbs_linecurve.h
    ${OPENNURBS_DIR}/opennurbs_line.h
    ${OPENNURBS_DIR}/opennurbs_linestyle.h
    ${OPENNURBS_DIR}/opennurbs_linetype.h
    ${OPENNURBS_DIR}/opennurbs_lookup.h
    ${OPENNURBS_DIR}/opennurbs_mapchan.h
    ${OPENNURBS_DIR}/opennurbs_material.h
    ${OPENNURBS_DIR}/opennurbs_math.h
    ${OPENNURBS_DIR}/opennurbs_matrix.h
    ${OPENNURBS_DIR}/opennurbs_memory.h
    ${OPENNURBS_DIR}/opennurbs_mesh.h
    ${OPENNURBS_DIR}/opennurbs_nurbscurve.h
    ${OPENNURBS_DIR}/opennurbs_nurbssurface.h
    ${OPENNURBS_DIR}/opennurbs_object.h
    ${OPENNURBS_DIR}/opennurbs_object_history.h
    ${OPENNURBS_DIR}/opennurbs_objref.h
    ${OPENNURBS_DIR}/opennurbs_offsetsurface.h
    ${OPENNURBS_DIR}/opennurbs_optimize.h
    ${OPENNURBS_DIR}/opennurbs_plane.h
    ${OPENNURBS_DIR}/opennurbs_planesurface.h
    ${OPENNURBS_DIR}/opennurbs_pluginlist.h
    ${OPENNURBS_DIR}/opennurbs_pointcloud.h
    ${OPENNURBS_DIR}/opennurbs_pointgeometry.h
    ${OPENNURBS_DIR}/opennurbs_pointgrid.h
    ${OPENNURBS_DIR}/opennurbs_point.h
    ${OPENNURBS_DIR}/opennurbs_polycurve.h
    ${OPENNURBS_DIR}/opennurbs_polyedgecurve.h
    ${OPENNURBS_DIR}/opennurbs_polylinecurve.h
    ${OPENNURBS_DIR}/opennurbs_polyline.h
    ${OPENNURBS_DIR}/opennurbs_qsort_template.h
    ${OPENNURBS_DIR}/opennurbs_rand.h
    ${OPENNURBS_DIR}/opennurbs_rendering.h
    ${OPENNURBS_DIR}/opennurbs_revsurface.h
    ${OPENNURBS_DIR}/opennurbs_rtree.h
    ${OPENNURBS_DIR}/opennurbs_sphere.h
    ${OPENNURBS_DIR}/opennurbs_string.h
    ${OPENNURBS_DIR}/opennurbs_sumsurface.h
    ${OPENNURBS_DIR}/opennurbs_surface.h
    ${OPENNURBS_DIR}/opennurbs_surfaceproxy.h
    ${OPENNURBS_DIR}/opennurbs_system.h
    ${OPENNURBS_DIR}/opennurbs_textlog.h
    ${OPENNURBS_DIR}/opennurbs_texture.h
    ${OPENNURBS_DIR}/opennurbs_texture_mapping.h
    ${OPENNURBS_DIR}/opennurbs_torus.h
    ${OPENNURBS_DIR}/opennurbs_unicode.h
    ${OPENNURBS_DIR}/opennurbs_userdata.h
    ${OPENNURBS_DIR}/opennurbs_uuid.h
    ${OPENNURBS_DIR}/opennurbs_version.h
    ${OPENNURBS_DIR}/opennurbs_viewport.h
    ${OPENNURBS_DIR}/opennurbs_workspace.h
    ${OPENNURBS_DIR}/opennurbs_xform.h
    ${OPENNURBS_DIR}/opennurbs_zlib.h
    ${OPENNURBS_DIR}/zlib/crc32.h
    ${OPENNURBS_DIR}/zlib/deflate.h
    ${OPENNURBS_DIR}/zlib/inffast.h
    ${OPENNURBS_DIR}/zlib/inffixed.h
    ${OPENNURBS_DIR}/zlib/inflate.h
    ${OPENNURBS_DIR}/zlib/inftrees.h
    ${OPENNURBS_DIR}/zlib/trees.h
    ${OPENNURBS_DIR}/zlib/zconf.h
    ${OPENNURBS_DIR}/zlib/zlib.h
    ${OPENNURBS_DIR}/zlib/zutil.h
)

add_library(opennurbs SHARED ${SOURCE_H} ${SOURCE_CPP})


